# Inspired by https://docs.docker.com/compose/django/
version: '3'

services:
  db:
    # NOTE: No persistance storage configured.
    # See: https://hub.docker.com/_/postgres/
    image: postgres
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    # NOTE: this works for bitnami, not sure if this works for regular
    # postgres image
    volumes:
      - ./docker-init-db.sql:/docker-entrypoint-initdb.d/init_db.sql

  redis:
    image: redis:5-alpine

  web:
    build: .
    image: scrumteamzgw/doc
    environment:
      - DJANGO_SETTINGS_MODULE=doc.conf.docker
      - SECRET_KEY=${SECRET_KEY:-myt*!t*9)9_&(qj*777=4js^@+ml@(_l2!j8p61_qg=3fb-*ew}
      - IS_HTTPS=0
      - ALLOWED_HOSTS=*
      - CACHE_DEFAULT=redis:6379/0
      - CACHE_AXES=redis:6379/0
    volumes:
      - ./src:/app/src
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis
