# Inspired by https://docs.docker.com/compose/django/
version: '3'

services:
  db:
    # NOTE: No persistance storage configured.
    # See: https://hub.docker.com/_/postgres/
    image: postgres
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    # NOTE: this works for bitnami, not sure if this works for regular
    # postgres image
    volumes:
      - ./docker-init-db.sql:/docker-entrypoint-initdb.d/init_db.sql

  redis:
    image: redis:5-alpine

  web:
    build: .
    image: scrumteamzgw/dowc:${TAG:-latest}
    environment:
      - DJANGO_SETTINGS_MODULE=dowc.conf.docker
      - SECRET_KEY=${SECRET_KEY:-&x#6%8mmd%-ujnqf-u9fcm_@0!n+k*x-muj)yrqo+cc6n)*tl2}
      - IS_HTTPS=0
      - ALLOWED_HOSTS=*
      - CACHE_DEFAULT=redis:6379/0
      - CACHE_AXES=redis:6379/0
    volumes:
      - ./src:/app/src
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis
