# Generated by Django 2.2.14 on 2021-03-03 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentfile",
            name="info_url",
            field=models.URLField(
                default="", help_text="Points the origin of where the document is used."
            ),
        ),
    ]
