# Generated by Django 2.2.14 on 2021-03-11 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentfile",
            name="info_url",
            field=models.URLField(
                default="", help_text="Points to the origin of the document's usage."
            ),
        ),
    ]
