# Generated by Django 2.2.20 on 2022-03-03 09:29

from django.db import migrations, models
from furl import furl


def populate_unversioned_url(apps, _):
    DocumentFile = apps.get_model("core", "documentfile")
    for df in DocumentFile.objects.all():
        df.unversioned_url = furl(df.drc_url).remove(args=True).url
        df.save()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_documentfile_info_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentfile",
            name="unversioned_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="URL-reference to the document in the Documents API. Does not include the `versie` query parameter.",
                verbose_name="Unversioned URL",
            ),
        ),
        migrations.RunPython(populate_unversioned_url, migrations.RunPython.noop),
    ]
