# Generated by Django 2.2.20 on 2022-03-03 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_documentfile_unversioned_url"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="documentfile",
            name="unique_write_drc_url",
        ),
        migrations.AlterField(
            model_name="documentfile",
            name="unversioned_url",
            field=models.URLField(
                help_text="URL-reference to the document in the Documents API. Does not include the `versie` query parameter.",
                verbose_name="Unversioned URL",
            ),
        ),
        migrations.AddConstraint(
            model_name="documentfile",
            constraint=models.UniqueConstraint(
                condition=models.Q(purpose="write"),
                fields=("unversioned_url",),
                name="unique_write_unversioned_url",
            ),
        ),
    ]
