# Generated by Django 3.2.12 on 2022-06-26 18:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_auto_20220303_1034"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentLock",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("resource_path", models.TextField(max_length=512)),
                ("lockscope", models.CharField(max_length=256)),
                ("locktype", models.CharField(max_length=256)),
                ("depth", models.CharField(max_length=256)),
                ("timeout", models.IntegerField()),
                ("owner", models.CharField(max_length=256)),
                ("token", models.UUIDField(default=uuid.uuid4, unique=True)),
            ],
        ),
    ]
