# Generated by Django 3.2.12 on 2022-09-23 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_documentlock_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="coreconfig",
            name="non_adfs_login_enabled",
            field=models.BooleanField(
                default=True,
                help_text="A flag that allows non-ADFS login (True) or not (False).",
                verbose_name="Non-ADFS login enabled",
            ),
        ),
    ]
