# Generated by Django 3.2.12 on 2023-01-26 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_coreconfig_non_adfs_login_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentfile",
            name="zaak",
            field=models.URLField(
                default="", help_text="URL-reference of ZAAK related to document."
            ),
        ),
    ]
