# Generated by Django 3.2.12 on 2023-01-27 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_documentfile_zaak"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="documentfile",
            name="zaak",
        ),
    ]
