# Generated by Django 3.2.12 on 2023-11-10 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_auto_20230214_1513"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentfile",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("write", "Write"),
                    ("read", "Read"),
                    ("download", "Download"),
                ],
                default="read",
                help_text="Purpose of requesting the document.",
                max_length=8,
            ),
        ),
    ]
