# Generated by Django 3.2.12 on 2023-12-20 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_alter_documentfile_purpose"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentfile",
            name="zaak",
            field=models.URLField(
                blank=True,
                default="",
                help_text="URL-reference to ZAAK if associated to one.",
            ),
        ),
    ]
