# Generated by Django 3.2.12 on 2023-01-27 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApplicationToken",
            fields=[
                (
                    "token",
                    models.CharField(
                        max_length=40,
                        primary_key=True,
                        serialize=False,
                        verbose_name="token",
                    ),
                ),
                (
                    "contact_person",
                    models.CharField(
                        help_text="Name of the person in the organization who can access the API",
                        max_length=200,
                        verbose_name="contact person",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Email of the person, who can access the API",
                        max_length=254,
                        verbose_name="email",
                    ),
                ),
                (
                    "organization",
                    models.CharField(
                        blank=True,
                        help_text="Organization which has access to the API",
                        max_length=200,
                        verbose_name="organization",
                    ),
                ),
                (
                    "last_modified",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Last date when the token was modified",
                        verbose_name="last modified",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date when the token was created",
                        verbose_name="created",
                    ),
                ),
                (
                    "application",
                    models.CharField(
                        blank=True,
                        help_text="Application which has access to the API",
                        max_length=200,
                        verbose_name="application",
                    ),
                ),
                (
                    "administration",
                    models.CharField(
                        blank=True,
                        help_text="Administration which has access to the API",
                        max_length=200,
                        verbose_name="administration",
                    ),
                ),
                (
                    "can_force_close_documents",
                    models.BooleanField(
                        default=False, verbose_name="can force close documents"
                    ),
                ),
                (
                    "has_all_reading_rights",
                    models.BooleanField(
                        default=False, verbose_name="has all reading rights"
                    ),
                ),
            ],
            options={
                "verbose_name": "application token authorization",
                "verbose_name_plural": "application token authorizations",
            },
        ),
    ]
