# Generated by Django 2.2.14 on 2020-12-14 16:35

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DocumentFile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "username",
                    models.CharField(
                        help_text="Username of user requesting document.",
                        max_length=255,
                        verbose_name="Username",
                    ),
                ),
                (
                    "user_email",
                    models.EmailField(
                        help_text="Email address of user requesting document.",
                        max_length=254,
                        verbose_name="User email address",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        help_text="URL reference to the source document in the Documents API. May include the 'versie' querystring parameter.",
                        max_length=1000,
                        verbose_name="DRC URL",
                    ),
                ),
                (
                    "document",
                    models.FileField(
                        blank=True,
                        storage=django.core.files.storage.FileSystemStorage(
                            location="/home/daniel/Desktop/gemeenteutrecht/doc/media/documents"
                        ),
                        upload_to="documents",
                    ),
                ),
                (
                    "lock",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Lock that is provided by Documenten API when you need to edit a document.",
                        max_length=100,
                        verbose_name="lock hash",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document file",
                "verbose_name_plural": "Document files",
            },
        ),
    ]
