# Generated by Django 2.2.14 on 2020-12-23 13:24

from django.db import migrations
import doc.core.models
import privates.fields
import privates.storages


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentfile",
            name="document",
            field=privates.fields.PrivateMediaFileField(
                help_text="This document can be edited directly by MS Office applications.",
                storage=privates.storages.PrivateMediaFileSystemStorage(),
                upload_to=doc.core.models.create_new_document_path,
                verbose_name="This document is to be edited or read.",
            ),
        ),
        migrations.AlterField(
            model_name="documentfile",
            name="original_document",
            field=privates.fields.PrivateMediaFileField(
                help_text="The original document is used to check if the document is edited before updating the document on the Documenten API.",
                storage=privates.storages.PrivateMediaFileSystemStorage(),
                upload_to=doc.core.models.create_original_document_path,
                verbose_name="original document file",
            ),
        ),
    ]
