# Generated by Django 2.2.14 on 2020-12-18 11:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="documentfile", old_name="url", new_name="drc_url",
        ),
        migrations.AlterField(
            model_name="documentfile",
            name="purpose",
            field=models.CharField(
                choices=[("edit", "Edit"), ("read", "Read")],
                default="read",
                help_text="Purpose of requesting the document.",
                max_length=4,
            ),
        ),
        migrations.AlterField(
            model_name="documentfile",
            name="user",
            field=models.ForeignKey(
                help_text="User requesting the document.",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
