# Generated by Django 2.2.14 on 2020-12-21 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_auto_20201218_1226"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentfile",
            name="deletion",
            field=models.BooleanField(
                default=False,
                help_text="This object is marked for deletion.",
                verbose_name="Delete",
            ),
        ),
        migrations.AddField(
            model_name="documentfile",
            name="updated",
            field=models.BooleanField(
                default=False,
                help_text="The document associated to this object has been updated on the DRC.",
                verbose_name="Updated",
            ),
        ),
    ]
