# Generated by Django 2.2.14 on 2020-12-24 09:10

from django.db import migrations, models
import privates.fields
import privates.storages


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_auto_20201223_1424"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentfile",
            name="filename",
            field=models.CharField(
                default="",
                help_text="Filename of object on DRC API.",
                max_length=255,
                verbose_name="Filename",
            ),
        ),
        migrations.AlterField(
            model_name="documentfile",
            name="document",
            field=privates.fields.PrivateMediaFileField(
                help_text="This document can be edited directly by MS Office applications.",
                storage=privates.storages.PrivateMediaFileSystemStorage(),
                upload_to="",
                verbose_name="This document is to be edited or read.",
            ),
        ),
        migrations.AlterField(
            model_name="documentfile",
            name="original_document",
            field=privates.fields.PrivateMediaFileField(
                help_text="The original document is used to check if the document is edited before updating the document on the Documenten API.",
                storage=privates.storages.PrivateMediaFileSystemStorage(),
                upload_to="",
                verbose_name="original document file",
            ),
        ),
    ]
