# Generated by Django 2.2.14 on 2020-12-24 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_auto_20201224_1010"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="documentfile",
            constraint=models.UniqueConstraint(
                condition=models.Q(purpose="edit"),
                fields=("drc_url",),
                name="unique_edit_drc_url",
            ),
        ),
    ]
