# Generated by Django 2.2.14 on 2020-12-21 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_auto_20201221_1122"),
    ]

    operations = [
        migrations.RemoveField(model_name="documentfile", name="updated",),
        migrations.AlterField(
            model_name="documentfile",
            name="deletion",
            field=models.BooleanField(
                default=False,
                help_text="The document associated to this object has been updated on the DRC.",
                verbose_name="Updated",
            ),
        ),
    ]
