# Generated by Django 2.2.14 on 2020-12-21 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_auto_20201221_1201"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentfile",
            name="deletion",
            field=models.BooleanField(
                default=False,
                help_text="The document associated to this object has been updated on the DRC and is ready for deletion.",
                verbose_name="Delete",
            ),
        ),
    ]
