# Generated by Django 2.2.14 on 2020-12-25 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_auto_20201224_1108"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentfile",
            name="updates",
            field=models.IntegerField(
                default=0,
                help_text="After every save the updates is incremented by 1.",
                verbose_name="updates",
            ),
        ),
    ]
